services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80" # WordPress sẽ chạy trên cổng 8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306" # MySQL sẽ chạy trên cổng 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress